### ISSUE TITLE
turning off single_import_per_statement

### ISSUE THREAD

**Issue by mambax7** [lmc-eu/php-coding-standard#70]
How can I turn off the formatting of namespace use (I guess, it's the single_import_per_statement)?

I have currently:
```php
use Modules\Publisher\{
    Constants,
    Helper,
    Item,
    Utility
};
```
but when I use your coding standards, it converts it to this, which I don't want:

```php
use Modules\Publisher\Constants;
use Modules\Publisher\Helper;
use Modules\Publisher\Item;
use Modules\Publisher\Utility;
```
I've tried different things in the ecs.php, but I can't figure that out :( 

Thanks!

**Comment by OndraM** [comment]
Rules could be excluded using SKIP option, see README: https://github.com/lmc-eu/php-coding-standard#exclude-skip-checks-or-files

In this case you would exclude `PhpCsFixer\Fixer\Import\SingleImportPerStatementFixer::class`.

**Comment by mambax7** [comment]
Thank you!!!!
