### ISSUE TITLE
[BUG] SpecifyArgSeparatorFixer require type error argument

### ISSUE THREAD

**Issue by janbarasek** [lmc-eu/php-coding-standard#72]
Hello,

The `Lmc\CodingStandard\Fixer\SpecifyArgSeparatorFixer` rule contains a serious bug that in PHP 7.4 adds a second `null` argument to the `http_build_query()` function, which causes a type error.

Example test:

```diff
    ---------- begin diff ----------
--- Original
+++ New
@@ -105,7 +105,7 @@
             }
         }
 
-        return (string) $refererUri->withQuery(http_build_query($cleanQueryParts));
+        return (string) $refererUri->withQuery(http_build_query($cleanQueryParts, null, '&'));
     }
 
     private function invalidGridFilterSettings(): void

    ----------- end diff -----------
```

![Snímek obrazovky 2022-01-04 v 10 29 23](https://user-images.githubusercontent.com/4738758/148038112-512d5cf8-ae6b-4e47-bf94-3c175f16c52d.png)

![Snímek obrazovky 2022-01-04 v 10 29 43](https://user-images.githubusercontent.com/4738758/148038162-378b374f-d8c5-4b26-b60c-77b21ab273e7.png)

Thanks.

**Comment by OndraM** [comment]
@janbarasek Thanks for the report, have a look at #73.
